apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuganacar-deployment
  namespace: vuganacar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuganacar
  template:
    metadata:
      labels:
        app: vuganacar
    spec:
      containers:
        - name: vuganacar
          image: vuganacar:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
