// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwfkvsaralvwngkwszzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Zmt2c2FyYWx2d25na3dzenprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTk4NTMsImV4cCI6MjA2OTI3NTg1M30.c1kT9JftwJEDs5C9_PXKTpeS41O1Pxw6pYaDXnQ0hnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});